repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
-   repo: https://github.com/google/yapf
    rev: v0.33.0
    hooks:
      - id: yapf
        name: "yapf"
        args: [-i, --style, google]
